export const HomeProduct = [
  {
    id: 1,
    name: "Product1",
    price: "25",
    img: "img/p1.jpeg",
    cat: "",
    type: "featured",
  },
  {
    id: 2,
    name: "Product2",
    price: "15",
    img: "img/p2.jpeg",
    cat: "",
    type: "new",
  },
  {
    id: 3,
    name: "Product3",
    price: "25",
    img: "img/p3.jpeg",
    cat: "",
    type: "new",
  },
  {
    id: 4,
    name: "Product4",
    price: "25",
    img: "img/p4.jpeg",
    cat: "",
    type: "new",
  },
  {
    id: 5,
    name: "Product5",
    price: "25",
    img: "img/p5.jpeg",
    cat: "",
    type: "new",
  },
  {
    id: 6,
    name: "Product6",
    price: "25",
    img: "img/p6.jpeg",
    cat: "",
    type: "top",
  },
  {
    id: 7,
    name: "Product7",
    price: "25",
    img: "img/p7.jpeg",
    cat: "",
    type: "feaured",
  },
  {
    id: 8,
    name: "Product8",
    price: "25",
    img: "img/p8.jpeg",
    cat: "",
    type: "top",
  },
  {
    id: 9,
    name: "Product9",
    price: "25",
    img: "img/p9.jpeg",
    cat: "",
    type: "featured",
  },
  {
    id: 10,
    name: "Product10",
    price: "25",
    img: "img/p10.jpeg",
    cat: "",
    type: "top",
  },
  {
    id: 11,
    name: "Product11",
    price: "25",
    img: "img/p11.jpeg",
    cat: "",
    type: "featured",
  },
  {
    id: 12,
    name: "Product12",
    price: "25",
    img: "img/p12.jpeg",
    cat: "",
    type: "top",
  },
  {
    id: 13,
    name: "Product13",
    price: "25",
    img: "img/p13.jpeg",
    cat: "",
    type: "new",
  },
  {
    id: 14,
    name: "Product14",
    price: "25",
    img: "img/p14.jpeg",
    cat: "",
    type: "featured",
  },
  {
    id: 15,
    name: "Product15",
    price: "25",
    img: "img/p15.jpeg",
    cat: "",
    type: "top",
  },
  {
    id: 16,
    name: "Product16",
    price: "25",
    img: "img/p16.jpeg",
    cat: "",
    type: "featured",
  },
];
