export const HomeProduct = [
  {
    id: 1,
    name: "camera",
    price: "25",
    img: "img/p1.jpeg",
    cat: "camera",
    type: "featured",
  },
  {
    id: 2,
    name: "E-Metter",
    price: "15",
    img: "img/p2.jpeg",
    cat: "metter",
    type: "new",
  },
  {
    id: 3,
    name: "laptop",
    price: "25",
    img: "img/p3.jpeg",
    cat: "laptop",
    type: "new",
  },
  {
    id: 4,
    name: "printer",
    price: "25",
    img: "img/p4.jpeg",
    cat: "printer",
    type: "new",
  },
  {
    id: 5,
    name: "t-shirt",
    price: "25",
    img: "img/p5.jpeg",
    cat: "t-shirt",
    type: "new",
  },
  {
    id: 6,
    name: "desktop",
    price: "25",
    img: "img/p6.jpeg",
    cat: "desktop",
    type: "top",
  },
  {
    id: 7,
    name: "Product",
    price: "25",
    img: "img/p7.jpeg",
    cat: "",
    type: "feaured",
  },
  {
    id: 8,
    name: "watch",
    price: "25",
    img: "img/p8.jpeg",
    cat: "watch",
    type: "top",
  },
  {
    id: 9,
    name: "holder",
    price: "25",
    img: "img/p9.jpeg",
    cat: "holder",
    type: "featured",
  },
  {
    id: 10,
    name: "Product10",
    price: "25",
    img: "img/p10.jpeg",
    cat: "",
    type: "top",
  },
  {
    id: 11,
    name: "Product11",
    price: "25",
    img: "img/p11.jpeg",
    cat: "",
    type: "featured",
  },
  {
    id: 12,
    name: "headphone",
    price: "25",
    img: "img/p12.jpeg",
    cat: "headphone",
    type: "top",
  },
  {
    id: 13,
    name: "pen",
    price: "25",
    img: "img/p13.jpeg",
    cat: "pen",
    type: "new",
  },
  {
    id: 14,
    name: "note",
    price: "25",
    img: "img/p14.jpeg",
    cat: "note",
    type: "featured",
  },
  {
    id: 15,
    name: "calculator",
    price: "25",
    img: "img/p15.jpeg",
    cat: "calculator",
    type: "top",
  },
  {
    id: 16,
    name: "umbrella",
    price: "25",
    img: "img/p16.jpeg",
    cat: "umbrella",
    type: "featured",
  },
];
